/**
 * Scheduling setup — turns "run it at 9am" into a real schedule. Generates either
 * a crontab line (for a machine/VPS) or a GitHub Actions cron workflow (cloud, no
 * machine to keep on), or both. The `/health-schedule` skill / `schedule` command
 * asks the user for a time and calls these.
 *
 * Note: the engine is just a CLI, so "scheduling" is always external — this module
 * produces the config for whichever scheduler you use; it does not daemonize.
 */

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";

export interface ScheduleSpec {
  /** Local 24h time "HH:MM". */
  at: string;
  /** IANA timezone (e.g. "Asia/Kolkata"). Used to convert to UTC for GitHub Actions. */
  tz?: string;
  /** Explicit cron expression — overrides `at` when given. */
  cron?: string;
  /** Command the scheduler runs. */
  command?: string;
}

const DEFAULT_COMMAND = "npx health-check run --file-issues";

/** Parse "HH:MM" → {h, m}, validating range. */
function parseAt(at: string): { h: number; m: number } {
  const match = at.match(/^(\d{1,2}):(\d{2})$/);
  if (!match) throw new Error(`Invalid --at time "${at}". Use 24h "HH:MM", e.g. "09:00".`);
  const h = Number(match[1]);
  const m = Number(match[2]);
  if (h > 23 || m > 59) throw new Error(`Invalid time "${at}".`);
  return { h, m };
}

/** A daily cron expression "M H * * *" from a local HH:MM (no tz conversion). */
export function buildLocalCron(at: string): string {
  const { h, m } = parseAt(at);
  return `${m} ${h} * * *`;
}

/** Minutes a timezone is offset from UTC right now (positive = ahead of UTC). */
function tzOffsetMinutes(tz: string): number {
  // Compare the same instant rendered in UTC vs the target tz.
  const now = new Date();
  const utc = new Date(now.toLocaleString("en-US", { timeZone: "UTC" }));
  const local = new Date(now.toLocaleString("en-US", { timeZone: tz }));
  return Math.round((local.getTime() - utc.getTime()) / 60000);
}

/** A daily cron in UTC (what GitHub Actions needs) from a local HH:MM + tz. */
export function buildUtcCron(at: string, tz?: string): string {
  const { h, m } = parseAt(at);
  if (!tz) return `${m} ${h} * * *`; // assume already UTC
  const offset = tzOffsetMinutes(tz);
  let total = h * 60 + m - offset; // local → UTC
  total = ((total % 1440) + 1440) % 1440;
  return `${total % 60} ${Math.floor(total / 60)} * * *`;
}

/** The crontab line for a local scheduler. */
export function crontabLine(spec: ScheduleSpec, projectDir: string): string {
  const cron = spec.cron ?? buildLocalCron(spec.at);
  const cmd = spec.command ?? DEFAULT_COMMAND;
  return `${cron} cd ${projectDir} && ${cmd} >> health-check.log 2>&1`;
}

/** A ready-to-commit GitHub Actions cron workflow. */
export function githubActionsWorkflow(spec: ScheduleSpec): string {
  const cron = spec.cron ?? buildUtcCron(spec.at, spec.tz);
  const cmd = spec.command ?? DEFAULT_COMMAND;
  const tzNote = spec.tz ? ` (${spec.at} ${spec.tz})` : "";
  return `# Generated by health-check-plugin. Runs the health check on a schedule.
# GitHub Actions cron is always UTC: '${cron}'${tzNote}.
name: Health Check

on:
  schedule:
    - cron: "${cron}"
  workflow_dispatch: {}   # allow manual runs from the Actions tab

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - name: Run health check
        env:
          # Map your secrets here (must be set in repo Settings → Secrets):
          DATABASE_URL: \${{ secrets.DATABASE_URL }}
          HEALTH_DISCORD_WEBHOOK_URL: \${{ secrets.HEALTH_DISCORD_WEBHOOK_URL }}
          HEALTH_SLACK_WEBHOOK_URL: \${{ secrets.HEALTH_SLACK_WEBHOOK_URL }}
          HEALTH_GITHUB_REPO: \${{ github.repository }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: ${cmd}
`;
}

export interface GenerateResult {
  cronLine?: string;
  workflowPath?: string;
}

/** Write the requested schedule artifacts. */
export function generateSchedule(
  spec: ScheduleSpec,
  mode: "cron" | "github-actions" | "both",
  projectDir = process.cwd()
): GenerateResult {
  const result: GenerateResult = {};

  if (mode === "cron" || mode === "both") {
    result.cronLine = crontabLine(spec, projectDir);
  }
  if (mode === "github-actions" || mode === "both") {
    const path = resolve(projectDir, ".github/workflows/health-check.yml");
    if (!existsSync(dirname(path))) mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, githubActionsWorkflow(spec));
    result.workflowPath = path;
  }

  return result;
}
